server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/trainerDB
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} [%thread] [%X{transactionId}] %-5level %logger{36} - %msg%n"
  level:
   root: info
   org.hibernate.orm.jdbc.bind: trace
